version: '3.8'
services:
  app:
    build: .
    ports:
      - "8007:5000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/vocabulary.db
      - FLASK_ENV=production
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
