version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/vocabulary.db
      - FLASK_ENV=production
    restart: unless-stopped