"""Add sentence_mastery and context_type to learning_records

Revision ID: 048efe4e4ddb
Revises: 08ac24d00669
Create Date: 2025-07-07 00:12:42.676866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048efe4e4ddb'
down_revision = '08ac24d00669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_mastery', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('context_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_records', schema=None) as batch_op:
        batch_op.drop_column('context_type')
        batch_op.drop_column('sentence_mastery')

    # ### end Alembic commands ###
