"""Initial migration

Revision ID: 08ac24d00669
Revises: 
Create Date: 2025-07-06 14:55:36.659570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ac24d00669'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('pos', sa.String(length=20), nullable=True),
    sa.Column('definition_cn', sa.Text(), nullable=True),
    sa.Column('definition_en', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('pronunciation', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.String(length=10), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('source_article_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word', name='unique_user_word')
    )
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_word'), ['word'], unique=False)

    op.create_table('learning_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_records_vocabulary_id'), ['vocabulary_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_records_vocabulary_id'))
        batch_op.drop_index(batch_op.f('ix_learning_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_records_created_at'))

    op.drop_table('learning_records')
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_word'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_user_id'))

    op.drop_table('vocabulary')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
